Readme.md, ballerina.conf, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_endpoint.bal, gmail/gmail_transformers.bal, gmail/gmail_types.bal, gmail/gmail_util_functions.bal, gmail/tests/Readme.md, gmail/tests/test.bal
=> Add documentation annotations. Fix few minor issues

Readme.md, ballerina.conf, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_endpoint.bal, gmail/gmail_transformers.bal, gmail/gmail_types.bal, gmail/gmail_util_functions.bal, gmail/tests/Readme.md, gmail/tests/test.bal
=> Add changes for http Client endpoint

Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_data_mappings.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal, gmail/tests/Readme.md, gmail/tests/test.bal
Add ballerina 0.970.0-beta 1 changes.
sendMessage is redesigned with changes.
Proper error handling is added.
Use of constants.bal for magic strings.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Add ballerina 0.970.0-beta1 syntax chnages, sendMessage design changes and add proper error Handling.

Ballerina.toml, Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_endpoint.bal, gmail/tests/Readme.md
Add package.md review changes. 
Add error handling for message request content type not supported.
=> Add package.md review changes. 

Ballerina.toml, Readme.md, gmail/Package.md, gmail/tests/Readme.md
Update version.
add license to toml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> add license to toml.

gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_data_mappings.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal
=> Add new syntax changes. 

Ballerina.toml, Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_data_mappings.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal, gmail/tests/Readme.md, gmail/tests/test.bal
=> Update package.md, update syntax changes

Ballerina.toml, Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_data_mappings.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal, gmail/tests/Readme.md, gmail/tests/test.bal
=> Add optional parameters. Add map headers. Fix doc comments. Update md files.

gmail/Package.md, gmail/gmail_utils.bal
=> Add package md according to gold standard. Add Ballerina beta15 http changes.

gmail/Package.md
=> Add tag line to the top

Readme.md, gmail/gmail_utils.bal, gmail/tests/Readme.md
=> Fix for beta15 changes

gmail/Package.md
=> Fix review comments

Ballerina.toml, Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/tests/Readme.md
=> Update md files. Format docerina comments. Update version.

Ballerina.toml, Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_data_mappings.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal, gmail/tests/Readme.md, gmail/tests/test.bal
=> Update Ballerina version. Format Code. Add new functionalities.

Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/tests/Readme.md, gmail/tests/test.bal
=> Move test properties conf file. Update ballerina version. Update sendMessage() method.

Ballerina.toml, Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal, gmail/tests/test.bal
=> Add changes for ballerina v0.975.0 compatibility

Readme.md
=> Update markdown files

Readme.md
This PR adds Travis build status image to the repo.
=> Add Travis build status image

Ballerina.toml, Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal, gmail/tests/Readme.md
- Fix syntax issues
- Update markdown files and toml file for 0.980.0 release
=> Prepare connector for Ballerina 0.980.0 release

.travis.yml, Ballerina.toml, Readme.md, gmail/Package.md, gmail/tests/Readme.md
> Update GMail connector for 0.981.0 stable release
This PR depends on the following PR:
https://github.com/ballerina-platform/ballerina-lang/pull/9929/
=> Update for 0.981.0 release

Ballerina.toml, Readme.md, gmail/Package.md, gmail/gmail_connector.bal, gmail/gmail_constants.bal, gmail/gmail_data_mappings.bal, gmail/gmail_endpoint.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal, gmail/tests/Readme.md
Fix connector with latest ballerina changes.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Fix connector with latest ballerina changes

Readme.md, gmail/Package.md
=> Add missing instructions to provide OAuth credentials

Ballerina.toml, Readme.md, gmail/Module.md, gmail/gmail_connector.bal, gmail/gmail_data_mappings.bal, gmail/gmail_types.bal, gmail/gmail_utils.bal, gmail/tests/test.bal
Change the custom error to Ballerina error
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the custom error to Ballerina error

Readme.md, gmail/Module.md
Fixes https://github.com/wso2-ballerina/module-gmail/issues/50
=> Fix doc issues

Ballerina.toml, Readme.md, gmail/Module.md, gmail/gmail_endpoint.bal, gmail/gmail_utils.bal, gmail/tests/Readme.md
=> Fix connector for Ballerina 0.990.3

Ballerina.toml, Readme.md, gmail/Module.md, gmail/tests/test.bal
=> Fix code samples in the README.md

Ballerina.toml, Readme.md, gmail/Module.md, gmail/tests/Readme.md
=> Sync with ballerina 0.990.4

Ballerina.toml, Readme.md, gmail/Module.md, gmail/gmail_constants.bal, gmail/gmail_endpoint.bal, gmail/tests/Readme.md, gmail/tests/test.bal
Sync with ballerina 0.991.0.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Sync with ballerina 0.991.0

Readme.md
Fix doc issue.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> …
=> Fix doc issue

Ballerina.toml, src/gmail/Module.md, src/gmail/external_functions.bal, src/gmail/gmail_data_mappings.bal, src/gmail/gmail_endpoint.bal, src/gmail/gmail_utils.bal, src/gmail/tests/README.md, src/gmail/tests/main_test.bal
> To migrate the Gmail connector to Ballerina 1.0 (beta) version.
=> Migrate to Ballerina 1.0 (beta) version

Ballerina.lock
Updates the Ballerina.lock file with the new Ballerina Gmail connector version.
=> Update the Ballerina.lock file

src/gmail/Module.md
=> Modified Gmail Connector Module.md page

.travis.yml, Ballerina.lock, Ballerina.toml, Readme.md, src/googleapis.gmail/Module.md, src/googleapis.gmail/gmail_data_mappings.bal, src/googleapis.gmail/gmail_endpoint.bal, src/googleapis.gmail/gmail_utils.bal, src/googleapis.gmail/tests/main_test.bal
Migrate the connector to the new Ballerina version, Swan Lake. Resolves https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail/issues/75
=> Migrate to Ballerina Swan Lake

.github/workflows/ci.yml, .github/workflows/release.yml, Ballerina.toml
>Fixing the build issue in docker container GitHub workflow
=> Migration to Ballerina SLP5- Build Issue Fix

.github/workflows/release.yml
> Update release.yml as a workaround for issue#27405
=>  The temporary workaround for issue#27405

metadata/gmail.json
> To add display name for UI needs.
> Make available user friendly display names.
=> Added UI metadata json

.github/workflows/ci.yml, .github/workflows/release.yml, .travis.yml, Ballerina.toml, Module.md, Package.md, Readme.md, gmail_endpoint.bal, gmail_utils.bal, tests/README.md, tests/main_test.bal
=> Migration Swan Lake Preview8

.github/workflows/ci.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, Readme.md, gmail/Module.md, gmail/Package.md, gmail/data_mappings.bal, gmail/endpoint.bal, gmail/modules/listener/listener.bal, gmail/tests/main_test.bal, gmail/types.bal, samples/drafts/list_drafts.bal, samples/drafts/send_draft.bal, samples/messages/list_messages.bal, samples/messages/send_html_message.bal, samples/messages/send_text_message.bal, samples/threads/list_threads.bal
>  Fix https://github.com/wso2-enterprise/choreo/issues/4490
>  Fix https://github.com/wso2-enterprise/choreo/issues/4491
> Replace tuples with record types to return the values
> Replace json arrays with proper record types
=> Replace tuples and json array with proper record type

.github/workflows/ci.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, Readme.md, gmail/Dependencies.toml, gmail/Module.md, gmail/Package.md, gmail/data_mappings.bal, gmail/endpoint.bal, gmail/modules/listener/Dispatcher.bal, gmail/modules/listener/types.bal, gmail/tests/main_test.bal, gmail/types.bal, gmail/utils.bal, samples/drafts/create_draft.bal, samples/drafts/list_drafts.bal, samples/drafts/send_draft.bal, samples/drafts/update_draft.bal, samples/labels/update_label.bal, samples/list_history.bal, samples/messages/get_attachment.bal, samples/messages/list_messages.bal, samples/messages/read_message_with_attachments.bal, samples/messages/send_html_message.bal, samples/messages/send_text_message.bal
> Some record types in Gmail Connector contains default values for optional fields. This PR will refactor them: Resolves https://github.com/wso2-enterprise/choreo/issues/4319, https://github.com/wso2-enterprise/choreo/issues/4286.
> Remove default values from optional fields in records.
=> Refactor record types to remove default values

Readme.md, gmail/endpoint.bal, gmail/tests/main_test.bal, gmail/types.bal, gmail/utils.bal, samples/drafts/delete_draft.bal, samples/labels/delete_label.bal, samples/messages/delete_message.bal, samples/messages/trash_message.bal, samples/messages/untrash_message.bal, samples/threads/delete_thread.bal, samples/threads/trash_untrash_thread.bal
> Replace boolean return type with appropriate return types: Resolves https://github.com/wso2-enterprise/choreo/issues/4901.
> Replace boolean return type with appropriate return types.
=> Replace boolean with appropriate return types

gmail/Ballerina.toml, gmail/endpoint.bal, gmail/modules/listener/listener.bal, gmail/modules/listener/types.bal, gmail/types.bal, gradle.properties
> Update Display Annotations: Resolves https://github.com/wso2-enterprise/choreo/issues/4903.
> Update proper display annotations for Gmail connector
=> Update display annotation

gmail/Dependencies.toml, gmail/data_mappings.bal, gmail/endpoint.bal, gmail/modules/listener/Dispatcher.bal, gmail/modules/listener/http_service.bal, gmail/utils.bal
> Some remote functions are remaining non isolated methods. Make them all as isolated functions.
> Fix isolated function issues.
=> Fix isolated function issues

gmail/Dependencies.toml, gradle.properties
Bump dependency versions to ballerina slbeta2
=> Bump dependency versions for Ballerina SLBeta2

Readme.md, gmail/Ballerina.toml, gmail/Package.md, gmail/constants.bal, gmail/endpoint.bal, gmail/modules/listener/Dispatcher.bal, gmail/modules/listener/Module.md, gmail/modules/listener/constants.bal, gmail/modules/listener/http_service.bal, gmail/modules/listener/listener.bal, gmail/modules/listener/natives.bal, gmail/modules/listener/types.bal, gmail/stream_implementer.bal, gmail/tests/main_test.bal, gmail/types.bal, gradle.properties, java-wrapper/src/main/java/org/ballerinalang/googleapis/gmail/HttpNativeOperationHandler.java, samples/drafts/list_drafts.bal, samples/list_history.bal, samples/listener/trigger_on_label_removed_email.bal, samples/listener/trigger_on_new_labeled_email.bal, samples/listener/trigger_on_new_starred_email.bal, samples/listener/trigger_on_star_removed_email.bal, samples/messages/list_messages.bal, samples/threads/list_threads.bal
> Replace List return type with Stream. Minor corrections in listener: Resolves https://github.com/wso2-enterprise/choreo/issues/5951.
> Replace List return type with Stream.
> Resolve a null point exception issue in Listener.
> Validate subscription resource path in Listener request.
=> Replace List return type with Stream

gmail/constants.bal, gmail/data_mappings.bal, gmail/modules/listener/Dispatcher.bal, gmail/modules/listener/http_service.bal, gmail/modules/listener/listener.bal, gmail/modules/listener/natives.bal, gmail/modules/listener/util.bal, gmail/stream_implementer.bal, gmail/utils.bal, java-wrapper/src/main/java/org/ballerinalang/googleapis/gmail/NativeHttpToGmailAdaptor.java
- Fix https://github.com/wso2-enterprise/choreo/issues/6822
- Fix concurrency related warning in listener
- https://github.com/ballerina-platform/module-ballerinax-slack/pull/42
=> Fix listener concurrency warning

README.md, gmail/Dependencies.toml, gmail/Package.md
- Bump version to slbeta3 in Dependencies.toml, README.md and Package.md
JDK 11
Ballerina SLBeta3-SNAPSHOT
=> Bump versions for slbeta3 in master branch 

samples/drafts/create_draft.bal, samples/drafts/delete_draft.bal, samples/drafts/list_drafts.bal, samples/drafts/read_draft.bal, samples/drafts/send_draft.bal, samples/drafts/update_draft.bal, samples/get_user_profile.bal, samples/labels/create_label.bal, samples/labels/delete_label.bal, samples/labels/list_label.bal, samples/labels/update_label.bal, samples/list_history.bal, samples/messages/delete_message.bal, samples/messages/get_attachment.bal, samples/messages/list_messages.bal, samples/messages/modify_message.bal, samples/messages/read_message_with_attachments.bal, samples/messages/read_text_message.bal, samples/messages/send_html_message.bal, samples/messages/send_text_message.bal, samples/messages/trash_message.bal, samples/messages/untrash_message.bal, samples/threads/delete_thread.bal, samples/threads/list_threads.bal, samples/threads/modify_thread.bal, samples/threads/read_one_thread.bal, samples/threads/trash_untrash_thread.bal
> Initialize connector config and connector client inside the main function. Use check during client initialization.
> Refactor the code of samples to initialize connector config and connector client inside the main function and use `check` during client initialization.
=> Refactor the code of samples

samples/drafts/create_draft.bal, samples/drafts/delete_draft.bal, samples/drafts/list_drafts.bal, samples/drafts/read_draft.bal, samples/drafts/send_draft.bal, samples/drafts/update_draft.bal, samples/get_user_profile.bal, samples/labels/create_label.bal, samples/labels/delete_label.bal, samples/labels/list_label.bal, samples/labels/update_label.bal, samples/list_history.bal, samples/messages/delete_message.bal, samples/messages/get_attachment.bal, samples/messages/list_messages.bal, samples/messages/modify_message.bal, samples/messages/read_message_with_attachments.bal, samples/messages/read_text_message.bal, samples/messages/send_html_message.bal, samples/messages/send_text_message.bal, samples/messages/trash_message.bal, samples/messages/untrash_message.bal, samples/threads/delete_thread.bal, samples/threads/list_threads.bal, samples/threads/modify_thread.bal, samples/threads/read_one_thread.bal, samples/threads/trash_untrash_thread.bal
- Refactor the code of samples
- Fix https://github.com/wso2-enterprise/choreo/issues/7499
=> [SLBeta2] Refactor the code of samples

gmail/Ballerina.toml
This is to add the missing double qoute in Ballerina.toml
=> [Slbeta2] Update Ballerina.toml 

gmail/Dependencies.toml, gradle.properties
$title
JDK 11
Ballerina SLBeta3
=> Bump standard lib versions in Dependencies.toml

gradle.properties
Bump ballerinaLang version to 2.0.0-beta.3
=> Bump ballerinaLang version to 2.0.0-beta.3

.github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, README.md, gmail/Dependencies.toml
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
- Add slbeta4 migration changes
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
=> add slbeta4 migration command changes

gmail/Dependencies.toml, gmail/modules/listener/http_service.bal, gmail/modules/listener/listener.bal, gmail/modules/listener/simple_http_service.bal, gmail/modules/listener/util.bal, gmail/modules/listener/watch_scheduler.bal, gmail/stream_implementer.bal, gmail/utils.bal
Fix daily build failure in connector's listener service 
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/164
* Ballerina Version: SL Beta4
* Operating System: Ubuntu
* Java SDK: 11
=> Fix build issue related http Service

README.md, gmail/Ballerina.toml, gmail/Dependencies.toml, gmail/Package.md, gradle.properties
- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml
=> Prepapre for 2.1.0 release with SLBeta6

gmail/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
=> Re-generate Dependencies.toml with latest pack

gmail/Ballerina.toml, gmail/Dependencies.toml, gmail/Package.md, gradle.properties
- Bump version to `2.2.0`
- Update Ballerina version to `2201.0.0` in Package.md 
- Regenerate Dependencies.toml with `2201.0.0`
- Add `distribution = "2201.0.0"` in Ballerina.toml
=> Prepapre for 2.2.0 release with `2201.0.0`

.github/workflows/ci.yml, .github/workflows/daily-build.yml
Add code coverage information to the workflows
Fixes # ([issue](https://github.com/ballerina-platform/ballerina-extended-library/issues/271))
- Add code coverage information to the workflows
Tested in the CI workflow
* Ballerina Version: 2201.0.0
* Operating System: Ubuntu 20.04
* Java SDK: 11
=>  [2201.0.0] Add code coverage info to workflows

gmail/utils.bal
In some places  in this connector error messages only return custom messages. They don't have actual error messages. This fix add the actual error messages along with the error message which is returned to user.
Fixes  https://github.com/ballerina-platform/ballerina-extended-library/issues/291
=> Add actual errors in error message

.github/workflows/dev-stg-release.yml
As we have removed the gradle project structure from this repo, removing irrelevant steps from dev-stg rel workflow
=> Remove irrelevant steps from dev-stg rel workflow

gmail/Ballerina.toml, gmail/Dependencies.toml, gmail/Package.md, gmail/config-types.bal, gmail/endpoint.bal
* Update ConnectionConfig record
* Bump connector version and ballerina version in Ballerina.toml
* Bump ballerina version in Package.md
* Update Dependencies.toml with Ballerina 2201.2.0
=> Update ConnectionConfig record

gmail/config-types.bal, gmail/endpoint.bal
- Remove `clientConfig` from `OAuth2RefreshTokenGrantConfig`
=> Remove clientConfig from OAuth2RefreshTokenGrantConfig record

.github/workflows/dev-stg-release.yml, .github/workflows/release.yml, gmail/Ballerina.toml, gmail/Package.md
=> Bump bal version to 2201.2.1

README.md, gmail/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
=> Update Slack channel occurrences with Discord

gmail/Ballerina.toml, gmail/Dependencies.toml, gmail/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
=> Update to Ballerina version 2201.3.0

.github/workflows/ci.yml, .github/workflows/pull-request.yml, README.md
$title
Related to [#533](https://github.com/ballerina-platform/ballerina-extended-library/issues/533)
=> Generate code coverage reports using codecov

gmail/data_mappings.bal
Fixes: https://github.com/ballerina-platform/ballerina-extended-library/issues/543
- Changes the message.body.data type check to `string`
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version: 2201.7.0
* Operating System: Mac OSX
* Java SDK:  Java 11
=> Fix issue with extracting message body content

.github/workflows/dev-stg-release.yml, .github/workflows/release.yml, gmail/Ballerina.toml, gmail/Package.md
- Prepare for 3.5.0 release with 2201.7.0
- https://github.com/wso2-enterprise/choreo/issues/23069
=> Prepare for 3.5.0 release with 2201.7.0

.github/workflows/pull-request.yml, ballerina/Dependencies.toml, build.gradle, codecov.yml, examples/build.gradle, settings.gradle
$Subject
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
- One line describing the feature/improvement/fix made by this PR 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
=> Update pull request workflow to reuse centralized workflow

.github/workflows/build-with-bal-test-native.yml
> $Subject
Fixes # (issue)
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
- One line describing the feature/improvement/fix made by this PR 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
=> Remove additional build flags from GraalVm check workflow

ballerina/Dependencies.toml, examples/build.sh, gradle.properties
$Subject
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
=> Update gradle plugin version

ballerina/Dependencies.toml, ballerina/build.gradle
=> Remove Publishing to GitHub Packages

ballerina/build.gradle
=> Add any platform for publish

.github/workflows/build-with-bal-test-graalvm.yml
=> Skip examples for graalvm check

README.md, ballerina/Module.md, ballerina/Package.md, ballerina/tests/README.md, docs/setup/setup.md, docs/spec/spec.md, examples/README.md
=> Improve docs as per guidelines

ballerina/Dependencies.toml, gradle.properties
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/5769
N/A
=> Bump the Ballerina Gradle Plugin Version

.github/workflows/ci.yml, .github/workflows/dev-stage-release.yml, .github/workflows/trivy-scan.yml, README.md
=> Disable examples build for publish & add trivy scan

.github/workflows/trivy-scan.yml
=> Disable example build in trivy scan

.github/workflows/release.yml
=> Change the release template to connector template

README.md, ballerina/Module.md, ballerina/Package.md, ballerina/client.bal, ballerina/modules/oas/client.bal, ballerina/tests/test.bal, docs/open-api-spec/Sanitations.md, docs/spec/spec.md, examples/process-mails/main.bal, examples/reply-mails/main.bal, examples/search-threads/main.bal, examples/send-mails/main.bal
=> Regenerate client in 2201.8.3

.github/workflows/release.yml, ballerina/build.gradle
=> Anchor build on top of 2201.8.4

README.md
=> Make all images 50% of the width

.github/workflows/dev-stage-release.yml, README.md, ballerina/Module.md, ballerina/Package.md, changelog.md, examples/README.md, examples/process-mails/.github/README.md, examples/process-mails/Process customer feedback emails.md, examples/reply-mails/.github/README.md, examples/reply-mails/Automated Email Responses.md, examples/search-threads/.github/README.md, examples/search-threads/Email Thread Search.md, examples/send-mails/.github/README.md, examples/send-mails/Send Maintenance Break Emails.md
$subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/5878
=> Tweak documentation

ballerina/tests/test.bal
=> Add sleeptime between delete and verification to reduce intermittent failures

.github/workflows/daily-build.yml
=> Skip examples build during daily build

.github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/dev-stage-release.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, .github/workflows/trivy-scan.yml, docs/spec/sanitation.md, docs/spec/spec.md
=> Update repo name change of ballerina-library 

README.md, ballerina/Module.md, ballerina/Package.md
=> Add configurables to quickstart step

.github/workflows/build-with-bal-test-graalvm.yml
=> Use mock server for graalvm tests

gradle.properties
=> Fix group in gradle.properties

.github/workflows/build-with-bal-test-graalvm.yml
=> Fix graalvm workflow

.github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/dev-stage-release.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, .github/workflows/trivy-scan.yml, .gitignore, build.gradle, examples/build.gradle, settings.gradle
=> Improve gradle build

.github/workflows/dev-stage-release.yml
=> Remove example build in publish

.github/workflows/regenerate-connector.yml
=> Add generation path for regen workflow

.github/workflows/regenerate-connector.yml
This reverts commit 1030425c36dc7c322cb7bb154463126879837d3e.
Fixes:
=> Revert "Remove unnecessary paths"
